apiVersion: apps/v1
kind: Deployment

metadata:
        name:
        labels:
spec:
        replicas:
        selector:
                matchLabels:
                        app:
        template:
        strategy:
                type: (RollingUpdate|Recreate|canary|a/b testing)
